# Generated by Django 5.0.7 on 2024-07-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=20)),
                ('course_trainer', models.CharField(max_length=20)),
                ('course_careers', models.CharField(max_length=20)),
                ('course_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('course_description', models.CharField(max_length=50)),
                ('course_scores', models.PositiveSmallIntegerField()),
                ('course_duration', models.DurationField()),
                ('course_sessions', models.CharField(max_length=20)),
                ('course_students', models.CharField(max_length=20)),
            ],
        ),
    ]
