# Generated by Django 5.0.7 on 2024-07-16 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('class_trainer', models.CharField(max_length=20)),
                ('class_size', models.CharField(max_length=20)),
                ('class_motto', models.CharField(max_length=20)),
                ('class_routine', models.CharField(max_length=20)),
                ('class_vission', models.CharField(max_length=20)),
                ('class_goals', models.CharField(max_length=20)),
                ('class_equipment', models.CharField(max_length=20)),
                ('class_lessons', models.CharField(max_length=20)),
                ('course_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
